kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: local-pvc
  namespace: adnan
spec:
  accessModes: 
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  storageClassName: local-storage

